version: 1

stacks:
  - id: reflexology-stack
    name: Reflexology Infrastructure
    project_root: terraform
    terraform_version: "1.5"
    runner_image: public.ecr.aws/spacelift/runner-terraform:latest
